services:
  web:
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: "0.5"
        reservations:
          memory: 64m
    ports:
      - '8000:8000'
    networks:
      - app_network
    volumes:
      - ./app:/app


networks:
  app_network:
    driver: bridge
